export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const SET_INIT_INGREDIENTS_ERROR = 'SET_INIT_INGREDIENTS_ERROR';

export const PURCHASE_ORDER_LOADING = 'PURCHASE_ORDER_LOADING';
export const PURCHASE_ORDER_SUCCESS = 'SUBMIT_ORDER_FINISHED';
export const PURCHASE_ORDER_ERROR = 'SUBMIT_ORDER_ERROR';
export const INIT_PURCHASED = 'INIT_PURCHASED';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_ERROR = 'FETCH_ORDERS_ERROR';
export const FETCH_ORDERS_LOADING = 'FETCH_ORDERS_LOADING';

export const INIT_SIGN_UP = 'INIT_SIGN_UP';